export const INDIAN_BANKS = [
  'State Bank of India (SBI)',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Punjab National Bank (PNB)',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'Bank of India',
  'Indian Bank',
  'Central Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab & Sind Bank',
  'IDBI Bank',
  'IDFC First Bank',
  'IndusInd Bank',
  'Yes Bank',
  'Federal Bank',
  'RBL Bank',
  'South Indian Bank',
  'Karur Vysya Bank',
  'City Union Bank',
  'Bandhan Bank',
  'Jammu & Kashmir Bank',
  'DCB Bank',
  'Lakshmi Vilas Bank',
  'Dhanlaxmi Bank',
  'Post Office',
  'NBFC / Others',
];
